---
title: "Exploring Raster Data"
---


```{r}

library(dplyr)
library(sf)
library(bcmaps)
library(terra)



# read in the spatial file 

bou <- st_read(file.path("clean_data/scott_herd_subset.gpkg"), crs = 4326)

# check this is not only output as a csv 


# read in the aoi 
aoi <- st_read(file.path("clean_data/scott_aoi.gpkg"))
aoi_3005 <- st_transform(aoi, 3005)
crs(aoi_3005)
# check with Andy if this is 3005 or 84?

# create a snapped AOI to nearest 100
  bb <- sf::st_bbox(aoi_3005)

  ## Generate expanded bbox -- expands to neared 100m
  xmin <- floor(bb$xmin / 100)*100
  xmax <- ceiling(bb["xmax"] / 100) * 100
  ymin <- floor(bb$ymin / 100)*100
  ymax <- ceiling(bb["ymax"] / 100) * 100

  box <- matrix(c(xmin, ymin, xmin, ymax, xmax, ymax, xmax, ymin, xmin, ymin), ncol = 2, byrow = TRUE)
  box <- sf::st_polygon(list(box))
  box <- sf::st_sfc(box, crs=sf::st_crs(aoi))
  box <- sf::st_as_sf(box)

st_write(box, file.path("clean_data/scott_aoi_snap.gpkg"))
aoi <- box


# create a template raster 
template <- terra::rast(aoi , resolution = 20)
terra::values(template) <- 0

terra::writeRaster(template, file.path("clean_data", "template.tif"), overwrite = TRUE)

```

## Extract base data using the CDED dataset


```{r}

trim_raw <- bcmaps::cded_terra(aoi)

# lets look at the raster
trim_raw
res(trim_raw)

# note this is in WGS so we need to convert to 3005
 
trim_3005 <- project(trim_raw, template)


# still takes a while to download

terra::writeRaster(trim_3005, file.path("clean_data", "dem.tif"), overwrite = TRUE) 

# generate slope 
rslope <- terra::terrain(trim_3005, v = "slope", neighbors = 8, unit = "degrees") 

#terra::writeRaster(rslope, file.path(out_path, "slope.tif"), overwrite = TRUE) 

# generate aspect
aspect <- terra::terrain(trim_3005, v = "aspect", neighbors = 8,  unit = "degrees") 


# generate topographic roughness index
tri <- terra::terrain(trim_3005, v = "TRI",neighbors = 8)


rstack <- c(trim_3005, rslope, aspect, tri)

plot(rstack)

```
