project:
  type: website

website:
  title: "Using R for Wildlife Telemetry Data Analysis"
  navbar:
    background: secondary
    right:
      - icon: github
        href: https://github.com/ninoxconsulting/r-telemetry-workshop-nov-2023
        aria-label: GitHub
    left:
      - href: index.qmd
        text: Home
  repo-url: https://github.com/ninoxconsulting/r-telemetry-workshop-nov-2023
  repo-actions: [edit, issue]
  sidebar:
      style: docked
      search: true
      background: light
      contents:
        - section: "Intro to Telemetry Data and Visualization"
          contents:
            - intro-setup.qmd
            - intro-telemetry-data.qmd
            - spatial-data-viz.qmd
        - section: "Telemetry Analysis and Covariate Preparation"
          contents:
            - bc-data-catalogue.qmd
            - exploring-raster-data.qmd
            - extracting-base-data.qmd
            - rsf.qmd

# bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme:
      light:
        - flatly
        - style-light.scss
      dark:
        - darkly
        - style-dark.scss
    toc: true



