---
title: "Introduction and System Setup"
---


## overview of course 

Will include: 
- how to read in, clean, QA your telemetry data
- how to summarise your data (tables, figures, maps)
- how to leverage bc data catalogue (vector, raster)
- how to perform spatial operations to model covariates

Wont include: 
- methodological detail of telemetry methods ie DOP calculations
- wont be working with individual datasets (until Friday!)

You will require the following software installed and configured for the workshop.
Please have this set up and ready to go **before** we start.

## Computing requirements

You will need:

-   A laptop computer with administrative privileges
-   [R and RStudio](#install-r-and-rstudio)
-   [R package development toolchain](#install-r-package-development-tools)
-   [Several R packages](#packages)

### Install R and RStudio {#install-r-and-rstudio}

You will need:

-   R version \>= 4.2.0
-   RStudio \>= 2023.03.1

#### Install R

Download and install R for your operating system from <https://cloud.r-project.org/>.

#### Install R Studio

Download and install RStudio Desktop from <https://posit.co/download/rstudio-desktop/>.
This page should automatically offer you the version suitable for your operating system, but you can scroll down to find versions for all operating systems.

### Install packages {#packages}

## Install RStudio

## Install packages
